build:
	gcc -o server server.c filehelper.c result_msg.c
	gcc -o client client.c filehelper.c result_msg.c
test_sv:
	gcc -o server server.c filehelper.c result_msg.c
client:
	gcc -o client client.c filehelper.c result_msg.c
clean:
	rm -f server client
	rm -rf sf/*
