build:
	gcc -o server server.c filehelper.c 
	gcc -o client client.c filehelper.c 
test_sv:
	gcc -o server server.c filehelper.c 
client:
	gcc -o client client.c filehelper.c 
clean:
	rm -f server client
	rm -rf sf/*
